# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 256
  stride: 256
# Network config
masknet:
  n_blocks: 8
  n_repeats: 5
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
  conv_kernel_size: 7
# Training config
training:
  epochs: 500
  batch_size: 8
  num_workers: 4
  half_lr: yes
  early_stop: no
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: sep_clean
  nondefault_nsrc: 2
  mode: min
  fraction_of_examples_to_use_for_validation: 0.1